In [1]:
import pandas as pd
import numpy as np
import statsmodels

print("Python works!")
print("Pandas version:", pd.__version__)

Python works!
Pandas version: 1.5.3

In [2]:
import pandas as pd

df = pd.read_stata("../data/raw/Uzbekistan-2024-full-data.dta")

print(df.shape)

(1008, 340)

In [3]:
df.head()

,idstd,id,a4a,a6a,a2,a1c,a0,a3a,a6c,a7,...,a3,d1a2_v4,stratificationregioncode,stratificationsizecode,stratificationsectorcode,stratificationpanelcode,wstrict,wmedian,wweak,strata
0,1372275,2,Food,Small,East,Establishment,Manufacturing,East,12,No,...,50.000 to 250.000,1061,East,Small (5-19),Food,Panel,21.101807,26.549549,42.161896,202
1,1372276,6,Other Manufacturing,Medium,Center,Establishment,Manufacturing,Center,30,No,...,50.000 to 250.000,1702,Center,Medium (20-99),Other Manufacturing,Panel,55.521236,66.269096,67.648705,63
2,1372277,7,Other Manufacturing,Small,East,Establishment,Manufacturing,East,5,No,...,50.000 to 250.000,2220,East,Small (5-19),Other Manufacturing,Panel,89.856010,131.589737,153.120819,208
3,1372278,11,Textiles,Medium,East,Establishment,Manufacturing,East,140,No,...,Over 250.000 to 1 million,1393,East,Medium (20-99),Textiles,Panel,12.278679,21.053011,22.503181,218
4,1372279,12,Food,Medium,Central-East,Establishment,Manufacturing,Central-East,32,No,...,Over 250.000 to 1 million,2310,Central-East,Medium (20-99),Food,Panel,3.317076,4.357112,5.722478,174

In [4]:
df.columns.tolist()

['idstd',
 'id',
 'a4a',
 'a6a',
 'a2',
 'a1c',
 'a0',
 'a3a',
 'a6c',
 'a7',
 'panel',
 'a1a',
 'a14d',
 'a14m',
 'a14y',
 'a14h',
 'a14min',
 'a20y',
 'a20m',
 'a20d',
 'a1',
 'a12',
 'a7a',
 'a7b',
 'a11',
 'a7c',
 'a9',
 'b1',
 'b1x',
 'b1_UZB',
 'b3a',
 'b2a',
 'b2b',
 'b2c',
 'b2d',
 'b4',
 'b4a',
 'b5',
 'b6',
 'b6b',
 'b7',
 'b7a',
 'b8',
 'b8x',
 'c3',
 'c4',
 'c5',
 'c31',
 'c32',
 'c6',
 'c7',
 'c8a',
 'c8b',
 'c9a',
 'c9b',
 'c10',
 'c11',
 'c12',
 'c13',
 'c14',
 'c33',
 'c34',
 'c34b',
 'c34bx',
 'c152',
 'c162',
 'c172',
 'c35a',
 'c35b',
 'c22b',
 'c36',
 'c37',
 'c38',
 'c39',
 'c40a',
 'c40b',
 'c41a',
 'c41b',
 'c42',
 'c30a',
 'd1a1a',
 'd1a6a',
 'd1a6b',
 'd1a6c',
 'd1a6cx',
 'd1a3',
 'd2',
 'd2x',
 'n3',
 'n3x',
 'd3a',
 'd3b',
 'd3c',
 'd31x',
 'd32',
 'd4a',
 'd4b',
 'd33a',
 'd33b',
 'd342',
 'd342b',
 'd35',
 'd8',
 'd12a',
 'd12b',
 'd13',
 'd38x',
 'd39',
 'd14a',
 'd14b',
 'd40a',
 'd40b',
 'd412',
 'd412b',
 'd30a',
 'd30b',
 'o1',
 'o2',
 'o3a2',
 'o3b2',
 'j31',
 'r1',
 'r2',
 'r3',
 'r4',
 'r5',
 'r6',
 'r7',
 'r8',
 'r9',
 'r10',
 'r11',
 'e1',
 'e2b',
 'e312',
 'e6',
 'e11',
 'e32',
 'e33',
 'e34',
 'e30',
 'h1',
 'h2',
 'h32x',
 'h5',
 'h62x',
 'h8',
 'h9',
 'f1',
 'g6b',
 'g2',
 'g3',
 'g4',
 'g31',
 'g32',
 'g33',
 'g5a',
 'g5b',
 'g5bx',
 'g30a',
 'ge3',
 'ge3a',
 'ge7',
 'ge8d',
 'k3a',
 'k3bc',
 'k3e',
 'k3f',
 'k3hd',
 'k4',
 'n5a',
 'n5b',
 'k5a',
 'k5a1',
 'k5i',
 'k5i1',
 'k5bc',
 'k5bc1',
 'k5e',
 'k5e1',
 'k5f',
 'k5f1',
 'k5hdj',
 'k5hdj1',
 'k6',
 'k7',
 'k82',
 'k9',
 'k10',
 'k11',
 'k13',
 'k14a',
 'k14b',
 'k14c',
 'k14d',
 'k14e',
 'k15a',
 'k15b',
 'k15c',
 'k15d',
 'k162',
 'k17',
 'k20a1',
 'k31',
 'k32',
 'k21',
 'k33',
 'k342',
 'k342x',
 'k35',
 'k36',
 'k37',
 'k38',
 'k392',
 'k392x',
 'k40',
 'k30',
 'j2',
 'j3',
 'j4',
 'j5',
 'j32',
 'j33',
 'j34',
 'j35',
 'j36',
 'j37',
 'j38',
 'j39',
 'j40',
 'j6a',
 'j41',
 'j42',
 'j43',
 'j7a',
 'j7b',
 'j10',
 'j11',
 'j12',
 'j13',
 'j14',
 'j15',
 'j30a',
 'j30b',
 'j30c',
 'j30e',
 'j30f',
 'h30',
 'i30',
 'j30_taxrate_pos',
 'j30_taxadmin_pos',
 'j30_permit_pos',
 'j30_instability_pos',
 'j30_corruption_pos',
 'j30_courts_pos',
 'j30_crime_pos',
 'l1',
 'l2',
 'l3a',
 'l3b',
 'l4a1',
 'l4a2',
 'l4b',
 'l5a',
 'l5b',
 'l5',
 'l9b',
 'l9b1',
 'l10',
 'l11a',
 'l11a1',
 'l11b',
 'l11b1',
 'l12a',
 'l12a1',
 'l34',
 'l35',
 'l36',
 'l1a',
 'l6',
 'l6a',
 'l8',
 'l37',
 'l38a',
 'l38b',
 'l39',
 'l40',
 'l41',
 'l30a',
 'l30b',
 'l30c',
 'm1a',
 'm1a_finance_pos',
 'm1a_land_pos',
 'm1a_permit_pos',
 'm1a_corruption_pos',
 'm1a_courts_pos',
 'm1a_crime_pos',
 'm1a_trade_pos',
 'm1a_electricity_pos',
 'm1a_workforce_pos',
 'm1a_labor_pos',
 'm1a_instability_pos',
 'm1a_informal_pos',
 'm1a_taxadmin_pos',
 'm1a_taxrate_pos',
 'm1a_transport_pos',
 'n2a',
 'n2a2',
 'n2b',
 'n2k',
 'n2l',
 'n2e',
 'n2i',
 'n7a',
 'n11',
 'a15d',
 'a15m',
 'a15y',
 'a15h',
 'a15min',
 'a16',
 'a17',
 'a18',
 'a19h',
 'a19m',
 'a13',
 'a1d',
 'a3b',
 'a3c',
 'a3',
 'd1a2_v4',
 'stratificationregioncode',
 'stratificationsizecode',
 'stratificationsectorcode',
 'stratificationpanelcode',
 'wstrict',
 'wmedian',
 'wweak',
 'strata']

In [5]:
df[['a6a']].value_counts().sort_index()

a6a
Small     404
Medium    303
Large     301
dtype: int64

In [6]:
[x for x in df.columns if 'l1' in x.lower()]

['l1', 'l10', 'l11a', 'l11a1', 'l11b', 'l11b1', 'l12a', 'l12a1', 'l1a']

In [7]:
df[['l1', 'l10', 'l11a', 'l11b', 'l12a']].head(10)

   l1 l10 l11a l11b l12a
0  12  No  NaN  NaN  NaN
1  30  No  NaN  NaN  NaN
2  15  No  NaN  NaN  NaN
3  60  No  NaN  NaN  NaN
4  32  No  NaN  NaN  NaN
5   6  No  NaN  NaN  NaN
6   5  No  NaN  NaN  NaN
7  12  No  NaN  NaN  NaN
8  60  No  NaN  NaN  NaN
9  18  No  NaN  NaN  NaN

In [8]:
df['l1'].describe()

count     1008
unique     209
top          5
freq       112
Name: l1, dtype: int64

In [9]:
df['l1'].attrs

{}

In [10]:
df[['d2']].head(10)

              d2
0    740000000.0
1    125000000.0
2   3312829000.0
3  21400000000.0
4   7000000000.0
5    450000000.0
6    120000000.0
7   6000000000.0
8     40000000.0
9   6000000000.0

In [11]:
df['productivity'] = df['d2'] / df['l1']

df['productivity'].describe()

TypeError: unsupported operand type(s) for /: 'Categorical' and 'Categorical'

In [12]:
df['d2_num'] = pd.to_numeric(df['d2'].astype(str), errors='coerce')
df['l1_num'] = pd.to_numeric(df['l1'].astype(str), errors='coerce')

In [13]:
df[['d2_num', 'l1_num']].head()

         d2_num  l1_num
0  7.400000e+08    12.0
1  1.250000e+08    30.0
2  3.312829e+09    15.0
3  2.140000e+10    60.0
4  7.000000e+09    32.0

In [14]:
df[['d2_num', 'l1_num']].isna().sum()

d2_num    99
l1_num    26
dtype: int64

In [15]:
df['l1_num'].value_counts().loc[lambda x: x.index == 0]

Series([], Name: l1_num, dtype: int64)

In [16]:
df['productivity'] = df['d2_num'] / df['l1_num']
df['productivity'].describe()

count    9.000000e+02
mean     5.596238e+10
std      8.329606e+11
min      4.000000e+03
25%      2.500000e+07
50%      8.582589e+07
75%      2.694906e+08
max      2.083333e+13
Name: productivity, dtype: float64

In [17]:
df['productivity'].quantile([0.01, 0.05, 0.25, 0.50, 0.75, 0.95, 0.99])

0.01    1.738677e+05
0.05    1.495000e+06
0.25    2.500000e+07
0.50    8.582589e+07
0.75    2.694906e+08
0.95    2.229201e+09
0.99    1.194756e+11
Name: productivity, dtype: float64

In [18]:
df[['d2_num', 'l1_num', 'productivity']].sort_values('productivity', ascending=False).head(10)

           d2_num  l1_num  productivity
877  2.500000e+14    12.0  2.083333e+13
527  5.600000e+13     5.0  1.120000e+13
215  5.000000e+13    10.0  5.000000e+12
689  3.500000e+13     8.0  4.375000e+12
374  7.672500e+13    21.0  3.653571e+12
260  4.840900e+13    18.0  2.689389e+12
879  1.513060e+14   100.0  1.513060e+12
722  3.700000e+11     2.0  1.850000e+11
825  1.521000e+13   110.0  1.382727e+11
71   1.670000e+13   140.0  1.192857e+11

In [20]:
df['log_productivity'] = np.log(df['productivity'])
df['log_productivity'].describe()

count    900.000000
mean      18.174109
std        2.353692
min        8.294050
25%       17.034386
50%       18.267830
75%       19.412043
max       30.667575
Name: log_productivity, dtype: float64

In [22]:
df['l1_num'].describe()

count     982.000000
mean       93.038697
std       224.139002
min         1.000000
25%        10.000000
50%        23.000000
75%        75.000000
max      2500.000000
Name: l1_num, dtype: float64

In [23]:
df['log_size'] = np.log(df['l1_num'])
df['log_size'].describe()

count    982.000000
mean       3.363581
std        1.402292
min        0.000000
25%        2.302585
50%        3.135494
75%        4.317488
max        7.824046
Name: log_size, dtype: float64

In [24]:
df[['log_size', 'log_productivity']].corr()

                  log_size  log_productivity
log_size           1.00000          -0.13842
log_productivity  -0.13842           1.00000

In [25]:
from scipy.stats import pearsonr

temp = df[['log_size', 'log_productivity']].dropna()
pearsonr(temp['log_size'], temp['log_productivity'])

PearsonRResult(statistic=-0.13842027748498853, pvalue=3.0875446455431494e-05)

In [27]:
import statsmodels.api as sm

reg_data = df[['log_productivity', 'log_size']].dropna()

X = sm.add_constant(reg_data['log_size'])
y = reg_data['log_productivity']

model_robust = sm.OLS(y, X).fit(cov_type='HC3')

print(model_robust.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:       log_productivity   R-squared:                       0.019
Model:                            OLS   Adj. R-squared:                  0.018
Method:                 Least Squares   F-statistic:                     13.94
Date:                Tue, 15 Sep 2026   Prob (F-statistic):           0.000201
Time:                        11:22:31   Log-Likelihood:                -2038.2
No. Observations:                 900   AIC:                             4080.
Df Residuals:                     898   BIC:                             4090.
Df Model:                           1
Covariance Type:                  HC3
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         18.9601      0.215     88.020      0.000      18.538      19.382
log_size      -0.2377      0.064     -3.733      0.000      -0.363      -0.113
==============================================================================
Omnibus:                      135.153   Durbin-Watson:                   1.950
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              669.894
Skew:                           0.584   Prob(JB):                    3.42e-146
Kurtosis:                       7.062   Cond. No.                         9.98
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

In [28]:
for col in df.columns:
    print(col)

idstd
id
a4a
a6a
a2
a1c
a0
a3a
a6c
a7
panel
a1a
a14d
a14m
a14y
a14h
a14min
a20y
a20m
a20d
a1
a12
a7a
a7b
a11
a7c
a9
b1
b1x
b1_UZB
b3a
b2a
b2b
b2c
b2d
b4
b4a
b5
b6
b6b
b7
b7a
b8
b8x
c3
c4
c5
c31
c32
c6
c7
c8a
c8b
c9a
c9b
c10
c11
c12
c13
c14
c33
c34
c34b
c34bx
c152
c162
c172
c35a
c35b
c22b
c36
c37
c38
c39
c40a
c40b
c41a
c41b
c42
c30a
d1a1a
d1a6a
d1a6b
d1a6c
d1a6cx
d1a3
d2
d2x
n3
n3x
d3a
d3b
d3c
d31x
d32
d4a
d4b
d33a
d33b
d342
d342b
d35
d8
d12a
d12b
d13
d38x
d39
d14a
d14b
d40a
d40b
d412
d412b
d30a
d30b
o1
o2
o3a2
o3b2
j31
r1
r2
r3
r4
r5
r6
r7
r8
r9
r10
r11
e1
e2b
e312
e6
e11
e32
e33
e34
e30
h1
h2
h32x
h5
h62x
h8
h9
f1
g6b
g2
g3
g4
g31
g32
g33
g5a
g5b
g5bx
g30a
ge3
ge3a
ge7
ge8d
k3a
k3bc
k3e
k3f
k3hd
k4
n5a
n5b
k5a
k5a1
k5i
k5i1
k5bc
k5bc1
k5e
k5e1
k5f
k5f1
k5hdj
k5hdj1
k6
k7
k82
k9
k10
k11
k13
k14a
k14b
k14c
k14d
k14e
k15a
k15b
k15c
k15d
k162
k17
k20a1
k31
k32
k21
k33
k342
k342x
k35
k36
k37
k38
k392
k392x
k40
k30
j2
j3
j4
j5
j32
j33
j34
j35
j36
j37
j38
j39
j40
j6a
j41
j42
j43
j7a
j7b
j10
j11
j12
j13
j14
j15
j30a
j30b
j30c
j30e
j30f
h30
i30
j30_taxrate_pos
j30_taxadmin_pos
j30_permit_pos
j30_instability_pos
j30_corruption_pos
j30_courts_pos
j30_crime_pos
l1
l2
l3a
l3b
l4a1
l4a2
l4b
l5a
l5b
l5
l9b
l9b1
l10
l11a
l11a1
l11b
l11b1
l12a
l12a1
l34
l35
l36
l1a
l6
l6a
l8
l37
l38a
l38b
l39
l40
l41
l30a
l30b
l30c
m1a
m1a_finance_pos
m1a_land_pos
m1a_permit_pos
m1a_corruption_pos
m1a_courts_pos
m1a_crime_pos
m1a_trade_pos
m1a_electricity_pos
m1a_workforce_pos
m1a_labor_pos
m1a_instability_pos
m1a_informal_pos
m1a_taxadmin_pos
m1a_taxrate_pos
m1a_transport_pos
n2a
n2a2
n2b
n2k
n2l
n2e
n2i
n7a
n11
a15d
a15m
a15y
a15h
a15min
a16
a17
a18
a19h
a19m
a13
a1d
a3b
a3c
a3
d1a2_v4
stratificationregioncode
stratificationsizecode
stratificationsectorcode
stratificationpanelcode
wstrict
wmedian
wweak
strata
d2_num
l1_num
productivity
log_productivity
log_size

In [29]:
# Show variables related to firm characteristics and productivity controls
keywords = [
    'age', 'export', 'finance', 'internet', 'technology',
    'ownership', 'region', 'location', 'foreign', 'industry'
]

matching_vars = [
    col for col in df.columns
    if any(keyword in col.lower() for keyword in keywords)
]

print(matching_vars)

['m1a_finance_pos', 'stratificationregioncode']

In [30]:
print(df.columns.tolist())

['idstd', 'id', 'a4a', 'a6a', 'a2', 'a1c', 'a0', 'a3a', 'a6c', 'a7', 'panel', 'a1a', 'a14d', 'a14m', 'a14y', 'a14h', 'a14min', 'a20y', 'a20m', 'a20d', 'a1', 'a12', 'a7a', 'a7b', 'a11', 'a7c', 'a9', 'b1', 'b1x', 'b1_UZB', 'b3a', 'b2a', 'b2b', 'b2c', 'b2d', 'b4', 'b4a', 'b5', 'b6', 'b6b', 'b7', 'b7a', 'b8', 'b8x', 'c3', 'c4', 'c5', 'c31', 'c32', 'c6', 'c7', 'c8a', 'c8b', 'c9a', 'c9b', 'c10', 'c11', 'c12', 'c13', 'c14', 'c33', 'c34', 'c34b', 'c34bx', 'c152', 'c162', 'c172', 'c35a', 'c35b', 'c22b', 'c36', 'c37', 'c38', 'c39', 'c40a', 'c40b', 'c41a', 'c41b', 'c42', 'c30a', 'd1a1a', 'd1a6a', 'd1a6b', 'd1a6c', 'd1a6cx', 'd1a3', 'd2', 'd2x', 'n3', 'n3x', 'd3a', 'd3b', 'd3c', 'd31x', 'd32', 'd4a', 'd4b', 'd33a', 'd33b', 'd342', 'd342b', 'd35', 'd8', 'd12a', 'd12b', 'd13', 'd38x', 'd39', 'd14a', 'd14b', 'd40a', 'd40b', 'd412', 'd412b', 'd30a', 'd30b', 'o1', 'o2', 'o3a2', 'o3b2', 'j31', 'r1', 'r2', 'r3', 'r4', 'r5', 'r6', 'r7', 'r8', 'r9', 'r10', 'r11', 'e1', 'e2b', 'e312', 'e6', 'e11', 'e32', 'e33', 'e34', 'e30', 'h1', 'h2', 'h32x', 'h5', 'h62x', 'h8', 'h9', 'f1', 'g6b', 'g2', 'g3', 'g4', 'g31', 'g32', 'g33', 'g5a', 'g5b', 'g5bx', 'g30a', 'ge3', 'ge3a', 'ge7', 'ge8d', 'k3a', 'k3bc', 'k3e', 'k3f', 'k3hd', 'k4', 'n5a', 'n5b', 'k5a', 'k5a1', 'k5i', 'k5i1', 'k5bc', 'k5bc1', 'k5e', 'k5e1', 'k5f', 'k5f1', 'k5hdj', 'k5hdj1', 'k6', 'k7', 'k82', 'k9', 'k10', 'k11', 'k13', 'k14a', 'k14b', 'k14c', 'k14d', 'k14e', 'k15a', 'k15b', 'k15c', 'k15d', 'k162', 'k17', 'k20a1', 'k31', 'k32', 'k21', 'k33', 'k342', 'k342x', 'k35', 'k36', 'k37', 'k38', 'k392', 'k392x', 'k40', 'k30', 'j2', 'j3', 'j4', 'j5', 'j32', 'j33', 'j34', 'j35', 'j36', 'j37', 'j38', 'j39', 'j40', 'j6a', 'j41', 'j42', 'j43', 'j7a', 'j7b', 'j10', 'j11', 'j12', 'j13', 'j14', 'j15', 'j30a', 'j30b', 'j30c', 'j30e', 'j30f', 'h30', 'i30', 'j30_taxrate_pos', 'j30_taxadmin_pos', 'j30_permit_pos', 'j30_instability_pos', 'j30_corruption_pos', 'j30_courts_pos', 'j30_crime_pos', 'l1', 'l2', 'l3a', 'l3b', 'l4a1', 'l4a2', 'l4b', 'l5a', 'l5b', 'l5', 'l9b', 'l9b1', 'l10', 'l11a', 'l11a1', 'l11b', 'l11b1', 'l12a', 'l12a1', 'l34', 'l35', 'l36', 'l1a', 'l6', 'l6a', 'l8', 'l37', 'l38a', 'l38b', 'l39', 'l40', 'l41', 'l30a', 'l30b', 'l30c', 'm1a', 'm1a_finance_pos', 'm1a_land_pos', 'm1a_permit_pos', 'm1a_corruption_pos', 'm1a_courts_pos', 'm1a_crime_pos', 'm1a_trade_pos', 'm1a_electricity_pos', 'm1a_workforce_pos', 'm1a_labor_pos', 'm1a_instability_pos', 'm1a_informal_pos', 'm1a_taxadmin_pos', 'm1a_taxrate_pos', 'm1a_transport_pos', 'n2a', 'n2a2', 'n2b', 'n2k', 'n2l', 'n2e', 'n2i', 'n7a', 'n11', 'a15d', 'a15m', 'a15y', 'a15h', 'a15min', 'a16', 'a17', 'a18', 'a19h', 'a19m', 'a13', 'a1d', 'a3b', 'a3c', 'a3', 'd1a2_v4', 'stratificationregioncode', 'stratificationsizecode', 'stratificationsectorcode', 'stratificationpanelcode', 'wstrict', 'wmedian', 'wweak', 'strata', 'd2_num', 'l1_num', 'productivity', 'log_productivity', 'log_size']

In [31]:
with open("variable_list.txt", "w") as f:
    for i, col in enumerate(df.columns):
        f.write(f"{i}: {col}\n")

print("Saved variable_list.txt")

Saved variable_list.txt

In [32]:
for i, col in enumerate(df.columns):
    if 0 <= i <= 120:
        print(i, col)

0 idstd
1 id
2 a4a
3 a6a
4 a2
5 a1c
6 a0
7 a3a
8 a6c
9 a7
10 panel
11 a1a
12 a14d
13 a14m
14 a14y
15 a14h
16 a14min
17 a20y
18 a20m
19 a20d
20 a1
21 a12
22 a7a
23 a7b
24 a11
25 a7c
26 a9
27 b1
28 b1x
29 b1_UZB
30 b3a
31 b2a
32 b2b
33 b2c
34 b2d
35 b4
36 b4a
37 b5
38 b6
39 b6b
40 b7
41 b7a
42 b8
43 b8x
44 c3
45 c4
46 c5
47 c31
48 c32
49 c6
50 c7
51 c8a
52 c8b
53 c9a
54 c9b
55 c10
56 c11
57 c12
58 c13
59 c14
60 c33
61 c34
62 c34b
63 c34bx
64 c152
65 c162
66 c172
67 c35a
68 c35b
69 c22b
70 c36
71 c37
72 c38
73 c39
74 c40a
75 c40b
76 c41a
77 c41b
78 c42
79 c30a
80 d1a1a
81 d1a6a
82 d1a6b
83 d1a6c
84 d1a6cx
85 d1a3
86 d2
87 d2x
88 n3
89 n3x
90 d3a
91 d3b
92 d3c
93 d31x
94 d32
95 d4a
96 d4b
97 d33a
98 d33b
99 d342
100 d342b
101 d35
102 d8
103 d12a
104 d12b
105 d13
106 d38x
107 d39
108 d14a
109 d14b
110 d40a
111 d40b
112 d412
113 d412b
114 d30a
115 d30b
116 o1
117 o2
118 o3a2
119 o3b2
120 j31

In [33]:
for start in range(0, 121, 20):
    print(f"\n--- {start} to {min(start+19, 120)} ---")
    for i in range(start, min(start+20, 121)):
        print(i, df.columns[i])

--- 0 to 19 ---
0 idstd
1 id
2 a4a
3 a6a
4 a2
5 a1c
6 a0
7 a3a
8 a6c
9 a7
10 panel
11 a1a
12 a14d
13 a14m
14 a14y
15 a14h
16 a14min
17 a20y
18 a20m
19 a20d

--- 20 to 39 ---
20 a1
21 a12
22 a7a
23 a7b
24 a11
25 a7c
26 a9
27 b1
28 b1x
29 b1_UZB
30 b3a
31 b2a
32 b2b
33 b2c
34 b2d
35 b4
36 b4a
37 b5
38 b6
39 b6b

--- 40 to 59 ---
40 b7
41 b7a
42 b8
43 b8x
44 c3
45 c4
46 c5
47 c31
48 c32
49 c6
50 c7
51 c8a
52 c8b
53 c9a
54 c9b
55 c10
56 c11
57 c12
58 c13
59 c14

--- 60 to 79 ---
60 c33
61 c34
62 c34b
63 c34bx
64 c152
65 c162
66 c172
67 c35a
68 c35b
69 c22b
70 c36
71 c37
72 c38
73 c39
74 c40a
75 c40b
76 c41a
77 c41b
78 c42
79 c30a

--- 80 to 99 ---
80 d1a1a
81 d1a6a
82 d1a6b
83 d1a6c
84 d1a6cx
85 d1a3
86 d2
87 d2x
88 n3
89 n3x
90 d3a
91 d3b
92 d3c
93 d31x
94 d32
95 d4a
96 d4b
97 d33a
98 d33b
99 d342

--- 100 to 119 ---
100 d342b
101 d35
102 d8
103 d12a
104 d12b
105 d13
106 d38x
107 d39
108 d14a
109 d14b
110 d40a
111 d40b
112 d412
113 d412b
114 d30a
115 d30b
116 o1
117 o2
118 o3a2
119 o3b2

--- 120 to 120 ---
120 j31

In [34]:
# Search variable names by World Bank Enterprise Survey code patterns
for prefix in ['b', 'c', 'd', 'e', 'f', 'g', 'h', 'j', 'k', 'l', 'm']:
    matches = [col for col in df.columns if col.startswith(prefix)]
    print(prefix, ":", matches)

b : ['b1', 'b1x', 'b1_UZB', 'b3a', 'b2a', 'b2b', 'b2c', 'b2d', 'b4', 'b4a', 'b5', 'b6', 'b6b', 'b7', 'b7a', 'b8', 'b8x']
c : ['c3', 'c4', 'c5', 'c31', 'c32', 'c6', 'c7', 'c8a', 'c8b', 'c9a', 'c9b', 'c10', 'c11', 'c12', 'c13', 'c14', 'c33', 'c34', 'c34b', 'c34bx', 'c152', 'c162', 'c172', 'c35a', 'c35b', 'c22b', 'c36', 'c37', 'c38', 'c39', 'c40a', 'c40b', 'c41a', 'c41b', 'c42', 'c30a']
d : ['d1a1a', 'd1a6a', 'd1a6b', 'd1a6c', 'd1a6cx', 'd1a3', 'd2', 'd2x', 'd3a', 'd3b', 'd3c', 'd31x', 'd32', 'd4a', 'd4b', 'd33a', 'd33b', 'd342', 'd342b', 'd35', 'd8', 'd12a', 'd12b', 'd13', 'd38x', 'd39', 'd14a', 'd14b', 'd40a', 'd40b', 'd412', 'd412b', 'd30a', 'd30b', 'd1a2_v4', 'd2_num']
e : ['e1', 'e2b', 'e312', 'e6', 'e11', 'e32', 'e33', 'e34', 'e30']
f : ['f1']
g : ['g6b', 'g2', 'g3', 'g4', 'g31', 'g32', 'g33', 'g5a', 'g5b', 'g5bx', 'g30a', 'ge3', 'ge3a', 'ge7', 'ge8d']
h : ['h1', 'h2', 'h32x', 'h5', 'h62x', 'h8', 'h9', 'h30']
j : ['j31', 'j2', 'j3', 'j4', 'j5', 'j32', 'j33', 'j34', 'j35', 'j36', 'j37', 'j38', 'j39', 'j40', 'j6a', 'j41', 'j42', 'j43', 'j7a', 'j7b', 'j10', 'j11', 'j12', 'j13', 'j14', 'j15', 'j30a', 'j30b', 'j30c', 'j30e', 'j30f', 'j30_taxrate_pos', 'j30_taxadmin_pos', 'j30_permit_pos', 'j30_instability_pos', 'j30_corruption_pos', 'j30_courts_pos', 'j30_crime_pos']
k : ['k3a', 'k3bc', 'k3e', 'k3f', 'k3hd', 'k4', 'k5a', 'k5a1', 'k5i', 'k5i1', 'k5bc', 'k5bc1', 'k5e', 'k5e1', 'k5f', 'k5f1', 'k5hdj', 'k5hdj1', 'k6', 'k7', 'k82', 'k9', 'k10', 'k11', 'k13', 'k14a', 'k14b', 'k14c', 'k14d', 'k14e', 'k15a', 'k15b', 'k15c', 'k15d', 'k162', 'k17', 'k20a1', 'k31', 'k32', 'k21', 'k33', 'k342', 'k342x', 'k35', 'k36', 'k37', 'k38', 'k392', 'k392x', 'k40', 'k30']
l : ['l1', 'l2', 'l3a', 'l3b', 'l4a1', 'l4a2', 'l4b', 'l5a', 'l5b', 'l5', 'l9b', 'l9b1', 'l10', 'l11a', 'l11a1', 'l11b', 'l11b1', 'l12a', 'l12a1', 'l34', 'l35', 'l36', 'l1a', 'l6', 'l6a', 'l8', 'l37', 'l38a', 'l38b', 'l39', 'l40', 'l41', 'l30a', 'l30b', 'l30c', 'l1_num', 'log_productivity', 'log_size']
m : ['m1a', 'm1a_finance_pos', 'm1a_land_pos', 'm1a_permit_pos', 'm1a_corruption_pos', 'm1a_courts_pos', 'm1a_crime_pos', 'm1a_trade_pos', 'm1a_electricity_pos', 'm1a_workforce_pos', 'm1a_labor_pos', 'm1a_instability_pos', 'm1a_informal_pos', 'm1a_taxadmin_pos', 'm1a_taxrate_pos', 'm1a_transport_pos']

In [35]:
print(df[['b5', 'b2a', 'b2b', 'b2c', 'b2d', 'd3a', 'e1', 'e2b', 'k3a', 'k6']].describe(include='all'))

          b5   b2a   b2b   b2c   b2d   d3a  \
count   1008  1008  1008  1008  1008  1008
unique    53    49    27    19    36    27
top     2018   100     0     0     0   100
freq      74   830   944   931   893   896

                                                       e1                e2b  \
count                                                1008                953
unique                                                  4                 34
top     Local â main product sold mostly in same mun...  Too many to count
freq                                                  632                674

         k3a    k6
count   1008  1008
unique    25     3
top      100   Yes
freq     657   696

In [36]:
print(df.attrs)

{}

In [37]:
print(df[['b5', 'b2a', 'b2b', 'b2c', 'b2d', 'd3a', 'e1', 'k6']].head(10).to_string())

     b5  b2a b2b b2c b2d  d3a                                                                                       e1   k6
0  2016  100   0   0   0  100  National â main product sold mostly across the country where establishment is located  Yes
1  2008  100   0   0   0  100  National â main product sold mostly across the country where establishment is located  Yes
2  2000  100   0   0   0  100  National â main product sold mostly across the country where establishment is located  Yes
3  2000  100   0   0   0   98  National â main product sold mostly across the country where establishment is located  Yes
4  2017   70   0  15  15  100   Local â main product sold mostly in same municipality where establishment is located   No
5  2017   60   0  15  25  100   Local â main product sold mostly in same municipality where establishment is located  Yes
6  2020  100   0   0   0  100   Local â main product sold mostly in same municipality where establishment is located  Yes
7  2014   75   0  15  10  100  National â main product sold mostly across the country where establishment is located   No
8  2007  100   0   0   0  100   Local â main product sold mostly in same municipality where establishment is located  Yes
9  1995  100   0   0   0  100   Local â main product sold mostly in same municipality where establishment is located   No

In [38]:
df['firm_age'] = df['a20y'] - pd.to_numeric(df['b5'].astype(str), errors='coerce')

print(df['firm_age'].describe())

count    991.000000
mean      12.347124
std       11.484491
min        0.000000
25%        5.000000
50%       10.000000
75%       16.000000
max      121.000000
Name: firm_age, dtype: float64

In [39]:
print(df['d1a2_v4'].value_counts(dropna=False))

4100    96
1410    94
1311    55
4730    32
4772    31
        ..
2391     1
2011     1
1101     1
3240     1
4761     1
Name: d1a2_v4, Length: 148, dtype: int64

In [40]:
print(df[['d3a', 'd3b', 'd3c']].head(15).to_string())

                         d3a                       d3b                       d3c
0                        100                         0                         0
1                        100                         0                         0
2                        100                         0                         0
3                         98                         0                         2
4                        100                         0                         0
5                        100                         0                         0
6                        100                         0                         0
7                        100                         0                         0
8                        100                         0                         0
9                        100                         0                         0
10  Don't know (spontaneous)  Don't know (spontaneous)  Don't know (spontaneous)
11                       100                         0                         0
12                       100                         0                         0
13                        80                         5                        15
14                       100                         0                         0

In [41]:
print(df['d3a'].value_counts(dropna=False).head(15))
print()
print(df['d3b'].value_counts(dropna=False).head(15))
print()
print(df['d3c'].value_counts(dropna=False).head(15))

100                         896
80                           13
Don't know (spontaneous)     13
0                            12
60                           11
50                           10
30                            7
40                            6
10                            5
20                            4
95                            4
90                            4
70                            4
75                            2
98                            2
Name: d3a, dtype: int64

0                           937
Don't know (spontaneous)     14
20                           10
50                            8
40                            7
10                            6
25                            5
60                            4
5                             3
15                            2
70                            2
90                            2
100                           2
2                             1
3                             1
Name: d3b, dtype: int64

0                           930
Don't know (spontaneous)     12
50                            7
20                            6
30                            6
100                           6
25                            5
80                            5
15                            3
40                            3
7                             2
70                            2
5                             2
2                             2
90                            2
Name: d3c, dtype: int64

In [42]:
print(df[['d3a', 'd3b', 'd3c']].head(20).to_string())

                         d3a                       d3b                       d3c
0                        100                         0                         0
1                        100                         0                         0
2                        100                         0                         0
3                         98                         0                         2
4                        100                         0                         0
5                        100                         0                         0
6                        100                         0                         0
7                        100                         0                         0
8                        100                         0                         0
9                        100                         0                         0
10  Don't know (spontaneous)  Don't know (spontaneous)  Don't know (spontaneous)
11                       100                         0                         0
12                       100                         0                         0
13                        80                         5                        15
14                       100                         0                         0
15                       100                         0                         0
16                       100                         0                         0
17                       100                         0                         0
18                        30                         0                        70
19                        70                        30                         0

In [43]:
print(df[['d3a', 'd3b', 'd3c']].info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1008 entries, 0 to 1007
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   d3a     1008 non-null   category
 1   d3b     1008 non-null   category
 2   d3c     1008 non-null   category
dtypes: category(3)
memory usage: 14.1 KB
None

In [44]:
df['export_status'] = (pd.to_numeric(df['d3c'].astype(str), errors='coerce') > 0).astype(int)

In [45]:
print(df[['d3a', 'd3b', 'd3c']].columns)

Index(['d3a', 'd3b', 'd3c'], dtype='object')

In [46]:
df['export_share'] = (
    pd.to_numeric(df['d3b'].astype(str), errors='coerce') +
    pd.to_numeric(df['d3c'].astype(str), errors='coerce')
)

print(df['export_share'].describe())

count    994.000000
mean       5.013078
std       17.987543
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max      100.000000
Name: export_share, dtype: float64

In [47]:
df['exporter'] = (df['export_share'] > 0).astype(int)

print(df['exporter'].value_counts())
print()
print(df['exporter'].value_counts(normalize=True) * 100)

0    910
1     98
Name: exporter, dtype: int64

0    90.277778
1     9.722222
Name: exporter, dtype: float64

In [48]:
print(df['k30'].value_counts(dropna=False).sort_index())

Don't know (spontaneous)      8
No obstacle                 603
Minor obstacle              272
Moderate obstacle           100
Major obstacle               19
Very severe obstacle          6
Name: k30, dtype: int64

In [49]:
df['finance_obstacle'] = df['k30'].map({
    'No obstacle': 0,
    'Minor obstacle': 1,
    'Moderate obstacle': 2,
    'Major obstacle': 3,
    'Very severe obstacle': 4
})

print(df['finance_obstacle'].value_counts(dropna=False).sort_index())

0.0    603
1.0    272
2.0    100
3.0     19
4.0      6
NaN      8
Name: finance_obstacle, dtype: int64

In [50]:
print([col for col in df.columns if 'internet' in col.lower() or 'website' in col.lower()])

[]

In [51]:
print([col for col in df.columns if col.startswith(('g', 'h', 'j', 'k'))])

['j31', 'h1', 'h2', 'h32x', 'h5', 'h62x', 'h8', 'h9', 'g6b', 'g2', 'g3', 'g4', 'g31', 'g32', 'g33', 'g5a', 'g5b', 'g5bx', 'g30a', 'ge3', 'ge3a', 'ge7', 'ge8d', 'k3a', 'k3bc', 'k3e', 'k3f', 'k3hd', 'k4', 'k5a', 'k5a1', 'k5i', 'k5i1', 'k5bc', 'k5bc1', 'k5e', 'k5e1', 'k5f', 'k5f1', 'k5hdj', 'k5hdj1', 'k6', 'k7', 'k82', 'k9', 'k10', 'k11', 'k13', 'k14a', 'k14b', 'k14c', 'k14d', 'k14e', 'k15a', 'k15b', 'k15c', 'k15d', 'k162', 'k17', 'k20a1', 'k31', 'k32', 'k21', 'k33', 'k342', 'k342x', 'k35', 'k36', 'k37', 'k38', 'k392', 'k392x', 'k40', 'k30', 'j2', 'j3', 'j4', 'j5', 'j32', 'j33', 'j34', 'j35', 'j36', 'j37', 'j38', 'j39', 'j40', 'j6a', 'j41', 'j42', 'j43', 'j7a', 'j7b', 'j10', 'j11', 'j12', 'j13', 'j14', 'j15', 'j30a', 'j30b', 'j30c', 'j30e', 'j30f', 'h30', 'j30_taxrate_pos', 'j30_taxadmin_pos', 'j30_permit_pos', 'j30_instability_pos', 'j30_corruption_pos', 'j30_courts_pos', 'j30_crime_pos']

In [52]:
print(df[['g6b', 'g2', 'g3', 'g4', 'g31', 'g32', 'g33', 'g5a', 'g5b']].head(10).to_string())

   g6b   g2    g3   g4  g31   g32         g33                       g5a  g5b
0    0   No   NaN  NaN   No   NaN         NaN                       NaN  NaN
1    0   No   NaN  NaN   No   NaN         NaN                       NaN  NaN
2    0  Yes  10.0   No  Yes  20.0  28000000.0                       NaN  NaN
3    0   No   NaN  NaN   No   NaN         NaN                       NaN  NaN
4    0   No   NaN  NaN   No   NaN         NaN                       NaN  NaN
5    0   No   NaN  NaN   No   NaN         NaN                       NaN  NaN
6  100   No   NaN  NaN   No   NaN         NaN                       NaN  NaN
7    0   No   NaN  NaN   No   NaN         NaN  Don't know (spontaneous)  NaN
8  100   No   NaN  NaN   No   NaN         NaN                       NaN  NaN
9    0   No   NaN  NaN   No   NaN         NaN  Don't know (spontaneous)  NaN

In [53]:
print(df[['c3', 'c4', 'c5', 'c31', 'c32', 'c6', 'c7', 'c8a', 'c8b', 'c9a', 'c9b',
          'c10', 'c11', 'c12', 'c13', 'c14', 'c33', 'c34', 'c34b', 'c152', 'c162', 'c172',
          'c35a', 'c35b', 'c22b']].head(10).to_string())

    c3   c4   c5                       c31    c32   c6   c7  c8a   c8b   c9a  c9b c10  c11 c12  c13  c14  c33                       c34          c34b c152 c162 c172 c35a c35b c22b
0   No  NaN  NaN                       NaN  10000   No  NaN  NaN   NaN   NaN  NaN  No  NaN  No  NaN  NaN  NaN                       500  Cubic meters   No  NaN  NaN  NaN  NaN   No
1   No  NaN  NaN                       NaN   1000   No  NaN  NaN   NaN   NaN  NaN  No  NaN  No  NaN  NaN  NaN  Don't know (spontaneous)           NaN   No  NaN  NaN  NaN  NaN   No
2  Yes  3.0   No                30000000.0  10000  Yes  3.0  0.0  30.0  None  NaN  No  NaN  No  NaN  NaN  NaN                        50  Cubic meters   No  NaN  NaN  NaN  NaN  Yes
3   No  NaN  NaN                       NaN   9000   No  NaN  NaN   NaN   NaN  NaN  No  NaN  No  NaN  NaN  NaN  Don't know (spontaneous)           NaN   No  NaN  NaN  NaN  NaN  Yes
4   No  NaN  NaN                       NaN   9500   No  NaN  NaN   NaN   NaN  NaN  No  NaN  No  NaN  NaN  NaN                      1800        Liters   No  NaN  NaN  NaN  NaN   No
5   No  NaN  NaN                       NaN   1200   No  NaN  NaN   NaN   NaN  NaN  No  NaN  No  NaN  NaN  NaN                       700        Liters   No  NaN  NaN  NaN  NaN   No
6  Yes  5.0   No                10000000.0    200  Yes  2.0  0.0   5.0   5.0  NaN  No  NaN  No  NaN  NaN  NaN                         1  Cubic meters   No  NaN  NaN  NaN  NaN  Yes
7   No  NaN  NaN                       NaN   9500   No  NaN  NaN   NaN   NaN  NaN  No  NaN  No  NaN  NaN  NaN  Don't know (spontaneous)           NaN   No  NaN  NaN  NaN  NaN   No
8  Yes  2.0   No  Don't know (spontaneous)    800   No  NaN  NaN   NaN   NaN  NaN  No  NaN  No  NaN  NaN  NaN  Don't know (spontaneous)           NaN   No  NaN  NaN  NaN  NaN   No
9   No  NaN  NaN                       NaN  10000   No  NaN  NaN   NaN   NaN  NaN  No  NaN  No  NaN  NaN  NaN                    350000        Liters   No  NaN  NaN  NaN  NaN   No

In [54]:
print(df['c22b'].value_counts(dropna=False))

No                          648
Yes                         341
Don't know (spontaneous)     19
Name: c22b, dtype: int64